from .state import State
from .district import District
from .unit_type import UnitType
from .unit import Unit
from .rank import Rank
from .designation import Designation
from .employee import Employee
from .act import Act
from .section import Section
from .crime_head import CrimeHead
from .crime_sub_head import CrimeSubHead
from .crime_head_act_section import CrimeHeadActSection
from .case_category import CaseCategory
from .gravity_offence import GravityOffence
from .occupation_master import Occupation
from .religion_master import Religion
from .caste_master import Caste
from .case_status_master import CaseStatus
from .court import Court
from .case_master import CaseMaster
from .victim import Victim
from .accused import Accused
from .complainant_details import Complainant
from .arrest_surrender import ArrestSurrender
from .chargesheet_details import ChargesheetDetails