"""add accused table

Revision ID: 066554bcca1e
Revises: 08d61b9483fc
Create Date: 2026-07-26 22:52:18.326553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066554bcca1e'
down_revision: Union[str, Sequence[str], None] = '08d61b9483fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accused',
    sa.Column('AccusedMasterID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=False),
    sa.Column('AccusedName', sa.String(length=255), nullable=False),
    sa.Column('AgeYear', sa.Integer(), nullable=False),
    sa.Column('GenderID', sa.String(length=10), nullable=False),
    sa.Column('PersonID', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['case_masters.CaseMasterID'], ),
    sa.PrimaryKeyConstraint('AccusedMasterID')
    )
    op.create_table('victims',
    sa.Column('VictimMasterID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=False),
    sa.Column('VictimName', sa.String(length=255), nullable=False),
    sa.Column('AgeYear', sa.Integer(), nullable=False),
    sa.Column('GenderID', sa.Integer(), nullable=False),
    sa.Column('VictimPolice', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['case_masters.CaseMasterID'], ),
    sa.PrimaryKeyConstraint('VictimMasterID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('victims')
    op.drop_table('accused')
    # ### end Alembic commands ###
