"""add case master table

Revision ID: 08d61b9483fc
Revises: 9049dea85bc2
Create Date: 2026-07-26 22:35:20.695358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d61b9483fc'
down_revision: Union[str, Sequence[str], None] = '9049dea85bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_masters',
    sa.Column('CaseMasterID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('CrimeNo', sa.String(length=30), nullable=False),
    sa.Column('CaseNo', sa.String(length=30), nullable=False),
    sa.Column('CrimeRegisteredDate', sa.Date(), nullable=False),
    sa.Column('PolicePersonID', sa.Integer(), nullable=False),
    sa.Column('PoliceStationID', sa.Integer(), nullable=False),
    sa.Column('CaseCategoryID', sa.Integer(), nullable=False),
    sa.Column('GravityOffenceID', sa.Integer(), nullable=False),
    sa.Column('CrimeMajorHeadID', sa.Integer(), nullable=False),
    sa.Column('CrimeMinorHeadID', sa.Integer(), nullable=False),
    sa.Column('CaseStatusID', sa.Integer(), nullable=False),
    sa.Column('CourtID', sa.Integer(), nullable=True),
    sa.Column('IncidentFromDate', sa.DateTime(), nullable=False),
    sa.Column('IncidentToDate', sa.DateTime(), nullable=False),
    sa.Column('InfoReceivedPSDate', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('BriefFacts', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['CaseCategoryID'], ['case_categories.CaseCategoryID'], ),
    sa.ForeignKeyConstraint(['CaseStatusID'], ['case_statuses.CaseStatusID'], ),
    sa.ForeignKeyConstraint(['CourtID'], ['courts.CourtID'], ),
    sa.ForeignKeyConstraint(['CrimeMajorHeadID'], ['crime_heads.CrimeHeadID'], ),
    sa.ForeignKeyConstraint(['CrimeMinorHeadID'], ['crime_sub_heads.CrimeSubHeadID'], ),
    sa.ForeignKeyConstraint(['GravityOffenceID'], ['gravity_offences.GravityOffenceID'], ),
    sa.ForeignKeyConstraint(['PolicePersonID'], ['Employee.EmployeeID'], ),
    sa.ForeignKeyConstraint(['PoliceStationID'], ['Unit.UnitID'], ),
    sa.PrimaryKeyConstraint('CaseMasterID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_masters')
    # ### end Alembic commands ###
