"""Add police module

Revision ID: 25028c8f863f
Revises: be08b294b12e
Create Date: 2026-07-26 20:21:39.690415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25028c8f863f'
down_revision: Union[str, Sequence[str], None] = 'be08b294b12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Designation',
    sa.Column('DesignationID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('DesignationName', sa.String(length=100), nullable=False),
    sa.Column('SortOrder', sa.Integer(), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('DesignationID')
    )
    op.create_table('Rank',
    sa.Column('RankID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('RankName', sa.String(length=100), nullable=False),
    sa.Column('Hierarchy', sa.Integer(), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('RankID')
    )
    op.create_table('Employee',
    sa.Column('EmployeeID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('DistrictID', sa.Integer(), nullable=False),
    sa.Column('UnitID', sa.Integer(), nullable=False),
    sa.Column('RankID', sa.Integer(), nullable=False),
    sa.Column('DesignationID', sa.Integer(), nullable=False),
    sa.Column('KGID', sa.String(length=30), nullable=False),
    sa.Column('FirstName', sa.String(length=150), nullable=False),
    sa.Column('EmployeeDOB', sa.Date(), nullable=False),
    sa.Column('GenderID', sa.Integer(), nullable=False),
    sa.Column('BloodGroupID', sa.Integer(), nullable=False),
    sa.Column('PhysicallyChallenged', sa.Boolean(), nullable=False),
    sa.Column('AppointmentDate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['DesignationID'], ['Designation.DesignationID'], ),
    sa.ForeignKeyConstraint(['DistrictID'], ['District.DistrictID'], ),
    sa.ForeignKeyConstraint(['RankID'], ['Rank.RankID'], ),
    sa.ForeignKeyConstraint(['UnitID'], ['Unit.UnitID'], ),
    sa.PrimaryKeyConstraint('EmployeeID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Employee')
    op.drop_table('Rank')
    op.drop_table('Designation')
    # ### end Alembic commands ###
