"""add lookup master tables

Revision ID: 2b5a09687ba3
Revises: 79bfb95a974f
Create Date: 2026-07-26 22:12:14.365766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5a09687ba3'
down_revision: Union[str, Sequence[str], None] = '79bfb95a974f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_categories',
    sa.Column('CaseCategoryID', sa.Integer(), nullable=False),
    sa.Column('LookupValue', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('CaseCategoryID')
    )
    op.create_table('case_statuses',
    sa.Column('CaseStatusID', sa.Integer(), nullable=False),
    sa.Column('CaseStatusName', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('CaseStatusID')
    )
    op.create_table('castes',
    sa.Column('caste_master_id', sa.Integer(), nullable=False),
    sa.Column('caste_master_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('caste_master_id')
    )
    op.create_table('gravity_offences',
    sa.Column('GravityOffenceID', sa.Integer(), nullable=False),
    sa.Column('LookupValue', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('GravityOffenceID')
    )
    op.create_table('occupations',
    sa.Column('OccupationID', sa.Integer(), nullable=False),
    sa.Column('OccupationName', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('OccupationID')
    )
    op.create_table('religions',
    sa.Column('ReligionID', sa.Integer(), nullable=False),
    sa.Column('ReligionName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ReligionID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('religions')
    op.drop_table('occupations')
    op.drop_table('gravity_offences')
    op.drop_table('castes')
    op.drop_table('case_statuses')
    op.drop_table('case_categories')
    # ### end Alembic commands ###
