"""Add UnitType

Revision ID: 2c4eb881ecb5
Revises: df1aa4869944
Create Date: 2026-07-26 19:47:38.569097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4eb881ecb5'
down_revision: Union[str, Sequence[str], None] = 'df1aa4869944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UnitType',
    sa.Column('UnitTypeID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('UnitTypeName', sa.String(length=100), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('UnitTypeID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UnitType')
    # ### end Alembic commands ###
