"""add court table

Revision ID: 53465b67065f
Revises: 2b5a09687ba3
Create Date: 2026-07-26 22:27:25.336527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53465b67065f'
down_revision: Union[str, Sequence[str], None] = '2b5a09687ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courts',
    sa.Column('CourtID', sa.Integer(), nullable=False),
    sa.Column('CourtName', sa.String(length=255), nullable=False),
    sa.Column('DistrictID', sa.Integer(), nullable=False),
    sa.Column('StateID', sa.Integer(), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['DistrictID'], ['District.DistrictID'], ),
    sa.ForeignKeyConstraint(['StateID'], ['State.StateID'], ),
    sa.PrimaryKeyConstraint('CourtID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courts')
    # ### end Alembic commands ###
