"""add crime master tables

Revision ID: 79bfb95a974f
Revises: 25028c8f863f
Create Date: 2026-07-26 21:26:25.643344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bfb95a974f'
down_revision: Union[str, Sequence[str], None] = '25028c8f863f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acts',
    sa.Column('ActCode', sa.String(length=20), nullable=False),
    sa.Column('ActDescription', sa.String(length=255), nullable=False),
    sa.Column('ShortName', sa.String(length=50), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ActCode')
    )
    op.create_table('crime_heads',
    sa.Column('CrimeHeadID', sa.Integer(), nullable=False),
    sa.Column('CrimeGroupName', sa.String(length=255), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('CrimeHeadID')
    )
    op.create_table('crime_sub_heads',
    sa.Column('CrimeSubHeadID', sa.Integer(), nullable=False),
    sa.Column('CrimeHeadID', sa.Integer(), nullable=False),
    sa.Column('CrimeHeadName', sa.String(length=255), nullable=False),
    sa.Column('SeqID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CrimeHeadID'], ['crime_heads.CrimeHeadID'], ),
    sa.PrimaryKeyConstraint('CrimeSubHeadID')
    )
    op.create_table('sections',
    sa.Column('ActCode', sa.String(length=20), nullable=False),
    sa.Column('SectionCode', sa.String(length=30), nullable=False),
    sa.Column('SectionDescription', sa.String(length=255), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ActCode'], ['acts.ActCode'], ),
    sa.PrimaryKeyConstraint('ActCode', 'SectionCode')
    )
    op.create_table('crime_head_act_sections',
    sa.Column('CrimeHeadID', sa.Integer(), nullable=False),
    sa.Column('ActCode', sa.String(length=20), nullable=False),
    sa.Column('SectionCode', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['ActCode', 'SectionCode'], ['sections.ActCode', 'sections.SectionCode'], ),
    sa.ForeignKeyConstraint(['CrimeHeadID'], ['crime_heads.CrimeHeadID'], ),
    sa.PrimaryKeyConstraint('CrimeHeadID', 'ActCode', 'SectionCode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crime_head_act_sections')
    op.drop_table('sections')
    op.drop_table('crime_sub_heads')
    op.drop_table('crime_heads')
    op.drop_table('acts')
    # ### end Alembic commands ###
