"""add complainants table

Revision ID: b9a363b8d7a1
Revises: 066554bcca1e
Create Date: 2026-07-26 23:02:21.699177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a363b8d7a1'
down_revision: Union[str, Sequence[str], None] = '066554bcca1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complainants',
    sa.Column('ComplainantID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=False),
    sa.Column('ComplainantName', sa.String(length=255), nullable=False),
    sa.Column('AgeYear', sa.Integer(), nullable=False),
    sa.Column('OccupationID', sa.Integer(), nullable=False),
    sa.Column('ReligionID', sa.Integer(), nullable=False),
    sa.Column('CasteID', sa.Integer(), nullable=False),
    sa.Column('GenderID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['case_masters.CaseMasterID'], ),
    sa.ForeignKeyConstraint(['CasteID'], ['castes.caste_master_id'], ),
    sa.ForeignKeyConstraint(['OccupationID'], ['occupations.OccupationID'], ),
    sa.ForeignKeyConstraint(['ReligionID'], ['religions.ReligionID'], ),
    sa.PrimaryKeyConstraint('ComplainantID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complainants')
    # ### end Alembic commands ###
