"""add chargesheet_details table

Revision ID: bc583c1edf07
Revises: d1edd2090812
Create Date: 2026-07-27 01:06:03.291791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc583c1edf07'
down_revision: Union[str, Sequence[str], None] = 'd1edd2090812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chargesheet_details',
    sa.Column('CSID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=False),
    sa.Column('csdate', sa.Date(), nullable=False),
    sa.Column('cstype', sa.String(length=1), nullable=False),
    sa.Column('PolicePersonID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['case_masters.CaseMasterID'], ),
    sa.ForeignKeyConstraint(['PolicePersonID'], ['Employee.EmployeeID'], ),
    sa.PrimaryKeyConstraint('CSID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chargesheet_details')
    # ### end Alembic commands ###
