"""Add Unit

Revision ID: be08b294b12e
Revises: 2c4eb881ecb5
Create Date: 2026-07-26 19:54:01.267938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be08b294b12e'
down_revision: Union[str, Sequence[str], None] = '2c4eb881ecb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Unit',
    sa.Column('UnitID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('UnitName', sa.String(length=150), nullable=False),
    sa.Column('TypeID', sa.Integer(), nullable=False),
    sa.Column('ParentUnit', sa.Integer(), nullable=True),
    sa.Column('NationalityID', sa.Integer(), nullable=False),
    sa.Column('StateID', sa.Integer(), nullable=False),
    sa.Column('DistrictID', sa.Integer(), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['DistrictID'], ['District.DistrictID'], ),
    sa.ForeignKeyConstraint(['ParentUnit'], ['Unit.UnitID'], ),
    sa.ForeignKeyConstraint(['StateID'], ['State.StateID'], ),
    sa.ForeignKeyConstraint(['TypeID'], ['UnitType.UnitTypeID'], ),
    sa.PrimaryKeyConstraint('UnitID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Unit')
    # ### end Alembic commands ###
