"""add arrest_surrenders table

Revision ID: d1edd2090812
Revises: 7242be44dc2f
Create Date: 2026-07-27 00:50:05.453139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1edd2090812'
down_revision: Union[str, Sequence[str], None] = '7242be44dc2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrest_surrenders',
    sa.Column('ArrestSurrenderID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=False),
    sa.Column('ArrestSurrenderTypeID', sa.Integer(), nullable=False),
    sa.Column('ArrestSurrenderDate', sa.Date(), nullable=False),
    sa.Column('ArrestSurrenderStateId', sa.Integer(), nullable=False),
    sa.Column('ArrestSurrenderDistrictId', sa.Integer(), nullable=False),
    sa.Column('PoliceStationID', sa.Integer(), nullable=False),
    sa.Column('IOID', sa.Integer(), nullable=False),
    sa.Column('CourtID', sa.Integer(), nullable=False),
    sa.Column('AccusedMasterID', sa.Integer(), nullable=False),
    sa.Column('IsAccused', sa.Boolean(), nullable=False),
    sa.Column('IsComplainantAccused', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['AccusedMasterID'], ['accused.AccusedMasterID'], ),
    sa.ForeignKeyConstraint(['ArrestSurrenderDistrictId'], ['District.DistrictID'], ),
    sa.ForeignKeyConstraint(['ArrestSurrenderStateId'], ['State.StateID'], ),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['case_masters.CaseMasterID'], ),
    sa.ForeignKeyConstraint(['CourtID'], ['courts.CourtID'], ),
    sa.ForeignKeyConstraint(['IOID'], ['Employee.EmployeeID'], ),
    sa.ForeignKeyConstraint(['PoliceStationID'], ['Unit.UnitID'], ),
    sa.PrimaryKeyConstraint('ArrestSurrenderID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arrest_surrenders')
    # ### end Alembic commands ###
