"""Create State table

Revision ID: df1aa4869944
Revises: 
Create Date: 2026-07-26 18:42:50.408140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1aa4869944'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('State',
    sa.Column('StateID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('StateName', sa.String(length=100), nullable=False),
    sa.Column('NationalityID', sa.Integer(), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('StateID')
    )
    op.create_table('District',
    sa.Column('DistrictID', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('DistrictName', sa.String(length=100), nullable=False),
    sa.Column('StateID', sa.Integer(), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['StateID'], ['State.StateID'], ),
    sa.PrimaryKeyConstraint('DistrictID')
    )
    op.drop_index(op.f('ix_demo_id'), table_name='demo')
    op.drop_table('demo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('demo_pkey'))
    )
    op.create_index(op.f('ix_demo_id'), 'demo', ['id'], unique=False)
    op.drop_table('District')
    op.drop_table('State')
    # ### end Alembic commands ###
